### ISSUE TITLE
Duplicate Switch Devices in v8

### ISSUE THREAD

**Issue by threeonparfive** [plasticrake/homebridge-tplink-smarthome#322] opened 2023-11-19 04:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have HS200s and HS220s, all of which have worked perfectly for a couple of years now, until upgrading to v8 today.  Now, Homebridge and HomeKit see duplicate devices for every switch.  For each switch, I see a "switch" and an "outlet" in both Homebridge and HomeKit, both with the same name, but none of the switches work.  They only function if you toggle the "outlet" instance.  This has broken many automations since they referenced the actual switch.

### What, if anything, has recently changed?

v8

### Version

8

### Node Version

v18.15.0

### Homebridge Version

1.7.0

### Which OS/Platform?

Other (Please describe)

### Relevant log output

```shell
Running native package on Synology NAS
```

### Configuration

```json
"name": "TplinkSmarthome",
            "addCustomCharacteristics": false,
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "platform": "TplinkSmarthome"
```

**Comment by timleeds15** [comment] 2023-11-19 13:33
temporary fix is to revert back to 7.0.1.  The dev is aware of the issue

**Comment by threeonparfive** [comment] 2023-11-19 13:45
> temporary fix is to revert back to 7.0.1. The dev is aware of the issue

I tried that but it didn't solve the issue...the mess of duplicates was still there.  I have ended up completely blowing the plugin and all 33 Kasa devices away, reinstalled the plugin (decided to try 8.0.1), and all seems well, for now at least.

**Comment by plasticrake** [comment] 2023-11-19 21:54
Issue with brightness and on/off fixed in d267e40ee0ab11f6182269dea16d5a0a2b328063 deff0549eb7c9d419a259257aa053f800e57b24a  `homebridge-tplink-smarthome@8.0.1`

I'll track the issue with duplicate devices here. Can someone with the issue please provide their `cachedAccessories` file?

**Comment by timleeds15** [comment] 2023-11-19 22:48
8.0.1-1 fixed all the issues for me. No more splitting of devices and the quick toggle on and off is working again! Homebridge still keeps saying theres a plug in update however. Could you push the prerelease as the newest version?

**Comment by pharrett** [comment] 2023-11-20 02:06
I was able to get around this for now by removing the switches from the accessory cache and restarting Homebridge.  This removed the duplicates but shows them as outlets instead of switches.  I currently just have two HS210 and one HS200.  I changed them to switches in the Home app and they working again.

**Comment by xstefanx** [comment] 2023-11-21 02:42
Started having this issue today. Here's my cachedAccessories file.
[.cachedAccessories.txt](https://github.com/plasticrake/homebridge-tplink-smarthome/files/13421203/default.cachedAccessories.txt)

Let me know if I can provide any further info. Willing to help test.

**Comment by rbclark** [comment] 2023-11-22 15:38
Just ran into this as well, reverting to 7.0.1 and restarting homebridge has fixed the problem for me for now.

**Comment by xstefanx** [comment] 2023-11-22 16:37
I had tried going to 7.1.0-next.0 and the issue was still present. Back to 7.0.1 fixed the issue for now. Homebridge itself was labeling these devices as outlets and HomeKit showed them as a group where the switch did nothing and the outlet controlled the switch

**Comment by salmundo11** [comment] 2023-11-23 01:32
I'm seeing the same issue. Will revert to v7.x

**Comment by peck4919** [comment] 2023-11-25 23:59
Same here. Reverted to 7.0.1 to resolve

**Comment by TassiRob** [comment] 2023-11-26 02:31
Also rolled back to 7.0.1
Tried deleting 7.0.1 plugin, removed the accessory folder and installed 8.0.1 in a child bridge. Attempt to add to HomeKit unsuccessful. Getting this message in logs after each plug was added:- Removing stale Characteristic: [Outlet.Brightness]

**Comment by wuddup** [comment] 2023-11-27 03:12
Here's another `cachedAccessories` sample. The `Hot Water Pump` device is the only one showing up as a duplicate switch/outlet (so far?)

[cachedAccessories.txt](https://github.com/plasticrake/homebridge-tplink-smarthome/files/13469364/cachedAccessories.txt)

**Comment by TinyMito** [comment] 2023-11-27 06:02
My HS210 appears to have a Light and an Outlet switch. The Light used to work, now it is not working and only the Outlet switch type works.

On my Homekit, it shows duplicated for the same HS210 switch.

**Comment by jlg89** [comment] 2023-11-29 14:57
Do you still need sample CachedAccessories files? I updated to 8.0.1 in two locations, both of which have a bunch of various switches and outlets; one location had zero issues, the other changed every switch to a switch+outlet combination, where the outlet was the functional part but the switch was associated with all the scenes & automations. Deleting the accessories from cache & restarting the bridge brought them back into HomeKit as normal switches, but everything had to be reconfigured.

**Comment by jlg89** [comment] 2023-11-29 18:34
The only real difference between the two installations that I can think of is that the installation with problems was set up at least a year, maybe two, before the installation that didn't have problems. So it's possible that this issue might have something to do with an old configuration parameter, or a format that changed awhile back.

**Comment by MrSco** [comment] 2023-12-05 14:08
v8.0.1 duplicates my outlets also. watching this thread for when there is a fix. until then v7.0.1 is working ok

**Comment by cefoster0** [comment] 2023-12-07 21:42
Same, reverted back to 7.0.1. My cachedAccessories file is multiple megabytes, let m know if I should just pull out the kasa items.

**Comment by shugass** [comment] 2023-12-16 19:49
Perhaps another clue for this one... when using any version above 7.0.1....
Along with the duplicates is another issue I just noticed....
Using "Controller for Homekit" app on iOS, previously I was able to set light dimmer levels without toggling the current state of the light, by adjusting brightness but not adjusting power on state. This is the holy grail of smart dimmer switches based on some research on the web discussions, since it can't be done natively with the kasa app or homekit. 
When updating to anything above 7.0.1 it is no longer possible to adjust brightness level without turning the light on. When I revert back to 7.0.1 it is once again possible to set brightness level without changing the current power state of the dimmer.
Thought this may be a clue or help figure out what is going on.
At first I thought it was the latest AppleTV update, but it is in fact the plugin version causing the change in behaviour.
Thanks!

**Comment by brsexton** [comment] 2023-12-17 15:45
I am seeing the same issue with my light switches when updating to version 8+. Reverting back to 7.0.1 corrected the problem.

**Comment by afunix** [comment] 2023-12-24 19:03
Still reproducible with v8.0.1

**Comment by kilakev** [comment] 2024-01-20 03:12
still seeing this issue. I see there's a pull request with a fix. How can we get this merged in?

**Closed** 2024-01-22 03:06 UTC
Labels: bug

**Comment by shugass** [comment] 2024-01-23 02:09
There is still strange behaviour present with current version 8.02 that started after version 7.0.1 and has been present since. When setting "only" brightness level, all versions after 7.0.1 turn the lights on when setting brightness. In 7.0.1 and previous you were able to set brightness without changing the current power state of the dimmer switch. I am doing this via "Controller for Homekit" as it is not possible to set brightness independant of power state using the stock apple "Home" app.
