### ISSUE TITLE
HS210 Switch shows as 2 accessories.

### ISSUE THREAD

**Issue by Papa-pp** [plasticrake/homebridge-tplink-smarthome#330] opened 2024-01-06 16:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When updates to 8.0.1 The HS210 switch shows as 2 accessories. Downgrade to 7.0.1 and switch shows as one switch

### What, if anything, has recently changed?

no

### Version

8.0.1

### Node Version

20.10.0

### Homebridge Version

1.7.0

### Which OS/Platform?

Windows

### Relevant log output

```shell
-
```

### Configuration

```json
{
    "name": "TplinkSmarthome",
    "addCustomCharacteristics": true,
    "deviceTypes": [
        "plug",
        "bulb"
    ],
    "devicesUseDiscoveryPort": false,
    "platform": "TplinkSmarthome",
    "_bridge": {
        "username": "0E:4C:47:10:EC:EA",
        "port": 42670
    }
}
```

**Comment by syl20bnr** [comment] 2024-01-07 04:10
Same here, HS200, HS210 and HS 220.

**Comment by syl20bnr** [comment] 2024-01-07 04:11
Duplicate of https://github.com/plasticrake/homebridge-tplink-smarthome/issues/322

**Comment by alicazi** [comment] 2024-01-17 06:56
Same here with HS200

**Comment by alicazi** [comment] 2024-01-17 07:05
FYI, I just noticed that this issue is duplicate of "Duplicate Switch Devices in v8 #322"

**Closed** 2024-01-22 03:06 UTC
Labels: bug
