### ISSUE TITLE
Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by nicoduj** [plasticrake/homebridge-tplink-smarthome#46] opened 2017-12-03 19:50 UTC
I got this error when homebridge restart. It seems I get rid of it after setting static IP address to the plugs.

### Current Behavior
The docker image crash at launch and restart (in loop) until I delete the accessories folder

### Steps to Reproduce (for bugs)
Restart the docker Image

### Versions

- **Node**:       `8.9.1`
- **Homebridge**: `0.4.33`
- **OS**:        Synology (oznu - docker - https://hub.docker.com/r/oznu/homebridge/ )

### Configuration

{
    "bridge": {
        "name": "Homebridge",
        "username": "BLABLA",
        "port":1234,
        "pin": "BLABLA"
    },

    "description": "This is an example configuration file. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
    ],

    "platforms": [
       	{
   		"platform": "HarmonyHub",
   		"name": "NicoHarmonyHub"
   		}
    ]
}

### Homebridge Log / Command Output

2017-12-03 06:50:20 | stdout | Disconnected from D-Bus, exiting.
-- | -- | --
2017-12-03 06:50:20 | stdout | at Socket.<anonymous> (/homebridge/node_modules/tplink-smarthome-api/lib/client.js:627:16)
2017-12-03 06:50:20 | stdout | at Client.createOrUpdateDeviceFromSysInfo (/homebridge/node_modules/tplink-smarthome-api/lib/client.js:686:12)
2017-12-03 06:50:20 | stdout | at Client.emit (/homebridge/node_modules/tplink-smarthome-api/lib/client.js:350:18)
2017-12-03 06:50:20 | stdout | at Client.emit (events.js:211:7)
2017-12-03 06:50:20 | stdout | at emitOne (events.js:116:13)
2017-12-03 06:50:20 | stdout | at Client.TplinkSmarthomePlatform.client.on (/homebridge/node_modules/homebridge-tplink-smarthome/lib/platform.js:60:12)
2017-12-03 06:50:20 | stdout | at TplinkSmarthomePlatform.addAccessory (/homebridge/node_modules/homebridge-tplink-smarthome/lib/platform.js:117:27)
2017-12-03 06:50:20 | stdout | at new PlugAccessory (/homebridge/node_modules/homebridge-tplink-smarthome/lib/plug.js:57:16)
2017-12-03 06:50:20 | stdout | at TplinkSmarthomePlatform.registerPlatformAccessory (/homebridge/node_modules/homebridge-tplink-smarthome/lib/platform.js:83:14)
2017-12-03 06:50:20 | stdout | at API.registerPlatformAccessories (/usr/local/share/.config/yarn/global/node_modules/homebridge/lib/api.js:159:8)
2017-12-03 06:50:20 | stdout | at API.emit (events.js:211:7)
2017-12-03 06:50:20 | stdout | at emitOne (events.js:116:13)
2017-12-03 06:50:20 | stdout | at Server.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/homebridge/lib/server.js:41:10)
2017-12-03 06:50:20 | stdout | at Server._handleRegisterPlatformAccessories (/usr/local/share/.config/yarn/global/node_modules/homebridge/lib/server.js:451:16)
2017-12-03 06:50:20 | stdout | at Bridge.Accessory.addBridgedAccessories (/usr/local/share/.config/yarn/global/node_modules/hap-nodejs/lib/Accessory.js:284:10)
2017-12-03 06:50:20 | stdout | at Bridge.Accessory.addBridgedAccessory (/usr/local/share/.config/yarn/global/node_modules/hap-nodejs/lib/Accessory.js:258:13)
2017-12-03 06:50:20 | stdout | Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 2959c9a2-e0b8-4b07-be50-8673b2559f4e
2017-12-03 06:50:20 | stdout |  
2017-12-03 06:50:20 | stdout | ^
2017-12-03 06:50:20 | stdout | throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);

**Comment by azebro** [comment] 2017-12-09 17:52
I have the same issue:


[2017-12-9 14:51:16] Homebridge is running on port 51826.
[2017-12-9 14:51:16] [TPLink] New Device Online: [Living Room Display] plug [8006F244AC4B8B0E414886C246BF80C3176B3C94] 192.168.1.191 9999
[2017-12-9 14:51:16] [TPLink] Adding: [Living Room Display] plug [8006F244AC4B8B0E414886C246BF80C3176B3C94]
[2017-12-9 14:51:16] [TPLink] New Device Online: [Left Lamp] plug [80063B286D17FAB2467374A4AEB8D4E817B02346] 192.168.1.67 9999
[2017-12-9 14:51:16] [TPLink] Adding: [Left Lamp] plug [80063B286D17FAB2467374A4AEB8D4E817B02346]
[2017-12-9 14:51:16] [TPLink] New Device Online: [Right Lamp] plug [8006BFB7D5C71261F3B32BDE5648F7C0176B4661] 192.168.1.172 9999
[2017-12-9 14:51:16] [TPLink] Adding: [Right Lamp] plug [8006BFB7D5C71261F3B32BDE5648F7C0176B4661]
[2017-12-9 14:51:16] [TPLink] New Device Online: [Living Room Flowers] plug [8006B6CDAC1EEAAFFBB821675973C94717656296] 192.168.1.116 9999
[2017-12-9 14:51:16] [TPLink] Adding: [Living Room Flowers] plug [8006B6CDAC1EEAAFFBB821675973C94717656296]
[2017-12-9 14:51:16] [homebridge-hs100.Hs100] New Device Online: [Living Room Display] plug [8006F244AC4B8B0E414886C246BF80C3176B3C94] 192.168.1.191 9999
[2017-12-9 14:51:16] [homebridge-hs100.Hs100] Adding: [Living Room Display] plug [8006F244AC4B8B0E414886C246BF80C3176B3C94]
/usr/lib/node_modules/hap-nodejs/lib/Accessory.js:258
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: e97b68ce-418b-4a34-af15-3e4ab4d005aa
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/hap-nodejs/lib/Accessory.js:258:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/lib/node_modules/hap-nodejs/lib/Accessory.js:284:10)
    at Server._handleRegisterPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:451:16)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:41:10)
    at API.emit (events.js:159:13)
    at API.registerPlatformAccessories (/usr/lib/node_modules/homebridge/lib/api.js:159:8)

**Comment by evilsparc** [comment] 2017-12-13 21:27
Same issue here. Only difference I can think of is that my container is running on a ReadyNAS box (Debian 8.9 as the underlying OS with Docker CE 17.09).

It doesn't seem to matter how I install the plugin (yarn vs npm install methods).

I opened an issue at the oznu repo page and was directed over here once the dev took a look at some logs. Happy to try and reopen that issue if you have something that suggests it would be worth tweaking the docker image instead. Thanks!

**Comment by smiffy1989** [comment] 2017-12-15 06:32
Been running fine for a while, started getting this yesterday too.

> Dec 15 06:22:06 homeserver homebridge[7174]: [12/15/2017, 6:22:06 AM] [TplinkSmarthome] Adding: [Dressing Room Plug] plug [800602E37F71168D1B400BE406943208187D8196]
> Dec 15 06:22:06 homeserver homebridge[7174]: /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:258
> Dec 15 06:22:06 homeserver homebridge[7174]:       throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
> Dec 15 06:22:06 homeserver systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
> Dec 15 06:22:06 homeserver systemd[1]: homebridge.service: Unit entered failed state.
> Dec 15 06:22:06 homeserver systemd[1]: homebridge.service: Failed with result 'exit-code'.
> Dec 15 06:22:10 homeserver systemd[1]: Stopped Node.js HomeKit Server.

NPM install on Ubuntu 16.04.2 LTS.

**Comment by MrTomAsh** [comment] 2017-12-19 21:45
Same issue here. Running on Raspberry Pi 3.

**Comment by phucyall** [comment] 2017-12-21 04:21
Same thing. Running on Raspberry Pi 1

**Comment by mattapperson** [comment] 2017-12-22 21:52
Same here

**Comment by crospa91** [comment] 2018-01-02 11:31
Same here, I've checked the cached accessories files and all the plug discovered by the plugin have the same Serial Number. Any suggestions on how to manually solve it temporary until a proper solution will be released?

**Comment by nicoduj** [comment] 2018-01-02 12:49
Hi, I don't have the problem anymore since I assigned a static IP address to the plugs.

**Comment by smiffy1989** [comment] 2018-01-02 14:30
Also added DHCP reservations on my router for each plug to get around this, been working fine for over 2 weeks.

**Comment by phucyall** [comment] 2018-01-02 16:02
I added 2 commands to the service startup script to delete the cached files before it actually launches the app.

**Comment by mattapperson** [comment] 2018-01-02 16:04
@phucyall doesn't that cause issues with any HomeKit automations you have setup?

**Comment by phucyall** [comment] 2018-01-02 16:07
@mattapperson My HomeKit doesn't complain and my scenarios all still work. That's the only automation I have set up. I also don't have any other plugins installed except this one because TPLink are the only ones I need to have bridged. I feel like the cause of these errors (trying to re-create the devices with same UUID each startup) is exactly what still allows it to works. The UUIDs stay the same.

**Comment by crospa91** [comment] 2018-01-02 18:02
My router already have the address reservation for the plugs, but every time I restart the container on docker I receive the UUID from homebridge. I don’t know what to do to sort it out...

**Comment by plasticrake** [comment] 2018-01-07 18:37
Hi Everyone! Finally got some time to look at this. I'm still not sure why the deviceId is not being stored in the context intermitantly seemingly out of nowhere, but I do have a workaround.

Instead of comparing the deviceId of the discovered device to the context deviceId, I'm using the UUID directly. This means I'm not using the context at all when matching up a discovered device to the homebridge cache.

Please leave feedback if v3.11.0 helps with this issue.  😸

**Comment by evilsparc** [comment] 2018-01-07 22:06
I seem to be having success with the workaround implemented. Multiple stops/kills and re/starts with no errors in the logs and things seem happy within HomeKit.

I am noticing a new warning in the logs:
`HAP Warning: Characteristic 00000053-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000003E-0000-1000-8000-0026BB765291. Adding anyway.` but it doesn't seem to be impacting any functionality. Happy to track down what this characteristic/service is that it's complaining about if it seems important and/or someone wants to give me a primer.

**Comment by plasticrake** [comment] 2018-01-11 18:16
@evilsparc I'm not seeing that message, but It refers to Characteristic.HardwareRevision. Are you sure its coming from this plugin?

**Comment by evilsparc** [comment] 2018-01-12 18:12
@plasticrake Apologies, after a little more digging it does look like that message is coming from somewhere else. In my excitement to have homebridge back up and running for its primary purpose (TP-Link devices), I overlooked that I also connected my Nest to the container right around the same time. My memory of when I added that plugin wasn't lining up, but a quick search for the HAP warning and that plugin brings up a full page of results so I'm guessing it's more than likely coming from there (and that I'm having a terrible time keeping track of when I installed things).

Btw, things are still running great with the update/workaround. :+1: Thanks again!

**Comment by plasticrake** [comment] 2018-01-12 18:42
@evilsparc Glad its still working! Since I haven't heard from anybody else I'll assume this issue is fixed for now. If anyone has more UUID issues that aren't resolved by a one time reset of the `cachedAccessories` file please open a new issue.

🎉

**Closed by plasticrake** 2018-01-12 18:42 UTC
