### ISSUE TITLE
error

### ISSUE THREAD

**Issue by roberkane212** [plasticrake/homebridge-tplink-smarthome#111] opened 2020-01-10 13:52 UTC
has anyone seen this error?

[homebridge-tplink-smarthome.TplinkSmarthome] Adding: [Raspberry Pi] plug [8006CC851C11856A6D023EA05E17EFA71B7EDC3E00]
[1/10/2020, 1:00:56 PM] TypeError: Cannot read property 'UUID' of undefined
    at HomeKitDevicePlug.addCharacteristic (/usr/local/lib/node_modules/homebridge-tplink-smarthome/lib/homekit-device/index.js:68:41)
    at HomeKitDevicePlug.addEnergyCharacteristics (/usr/local/lib/node_modules/homebridge-tplink-smarthome/lib/homekit-device/plug.js:112:10)
    at new HomeKitDevicePlug (/usr/local/lib/node_modules/homebridge-tplink-smarthome/lib/homekit-device/plug.js:19:12)
    at Function.create (/usr/local/lib/node_modules/homebridge-tplink-smarthome/lib/homekit-device/index.js:11:12)
    at new TplinkAccessory (/usr/local/lib/node_modules/homebridge-tplink-smarthome/lib/tplink-accessory.js:24:35)
    at createTplinkAccessory (/usr/local/lib/node_modules/homebridge-tplink-smarthome/lib/platform.js:74:10)
    at TplinkSmarthomePlatform.addAccessory (/usr/local/lib/node_modules/homebridge-tplink-smarthome/lib/platform.js:252:23)
    at Client.TplinkSmarthomePlatform.client.on.device (/usr/local/lib/node_modules/homebridge-tplink-smarthome/lib/platform.js:132:12)
    at Client.emit (events.js:198:13)
    at Client.emit (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:191:13)
    at process (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:604:14)
    at sysInfo.children.forEach.child (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:611:9)
    at Array.forEach (<anonymous>:null:null)
    at Client.createOrUpdateDeviceFromSysInfo (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:609:24)
    at Socket.socket.on (/usr/local/lib/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/lib/client.js:529:14)
    at Socket.emit (events.js:198:13)
    at UDP.onMessage (dgram.js:628:8)

**Comment by daberlin** [comment] 2020-01-10 14:02
Yes, I get exactly the same error!

It started after the upgrade to v5.
Then I deleted the cachedAccessories. No change after restart; same error.
After that I additionally deleted all files in the "persist" directory. Restart -> same error.

I ended up downgrading to the latest v4 version; works again.

**Comment by roberkane212** [comment] 2020-01-10 14:03
@daberlin do you have the command to downgrade?

**Comment by daberlin** [comment] 2020-01-10 14:04
sudo npm install -g homebridge-tplink-smarthome@4.0.1

**Comment by ssambhi900** [comment] 2020-01-10 14:13
I'm having the same issue since upgrading to 5.0


[1/10/2020, 9:12:12 AM] TypeError: Cannot read property 'UUID' of undefined
    at HomeKitDevicePlug.getCharacteristic (C:\Users\Administrator\AppData\Roami
ng\npm\node_modules\homebridge-tplink-smarthome\lib\homekit-device\index.js:75:4
8)
    at HomeKitDevicePlug.supportsCharacteristic (C:\Users\Administrator\AppData\
Roaming\npm\node_modules\homebridge-tplink-smarthome\lib\homekit-device\index.js
:58:17)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\homebridge-tplink
-smarthome\lib\tplink-accessory.js:181:25
    at Array.forEach (<anonymous>)
    at TplinkAccessory.setupCharacteristics (C:\Users\Administrator\AppData\Roam
ing\npm\node_modules\homebridge-tplink-smarthome\lib\tplink-accessory.js:180:21)

    at new TplinkAccessory (C:\Users\Administrator\AppData\Roaming\npm\node_modu
les\homebridge-tplink-smarthome\lib\tplink-accessory.js:132:12)
    at createTplinkAccessory (C:\Users\Administrator\AppData\Roaming\npm\node_mo
dules\homebridge-tplink-smarthome\lib\platform.js:74:10)
    at TplinkSmarthomePlatform.addAccessory (C:\Users\Administrator\AppData\Roam
ing\npm\node_modules\homebridge-tplink-smarthome\lib\platform.js:252:23)
    at Client.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modul

**Comment by marksthomas** [comment] 2020-01-10 14:23
This is a duplicate of this:-

https://github.com/plasticrake/homebridge-tplink-smarthome/issues/110

Solution is to download for the moment.

**Closed** 2020-04-19 21:20 UTC
